name: 🐛 Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - username
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Use the latest version of the tool
        - Test with a minimal reproduction case

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of git-security-audit are you running?
      placeholder: "v2.0.0 (run `git-security-audit --version`)"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What operating system are you using?
      options:
        - Ubuntu 24.04
        - Ubuntu 22.04
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - Windows (Git Bash)
        - Windows (WSL)
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: scan_type
    attributes:
      label: Scan Type
      description: What type of scan were you running?
      options:
        - quick
        - comprehensive 
        - secrets
        - files
        - compliance
        - custom pattern
    validations:
      required: true

  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is
      placeholder: "The tool crashed when scanning a repository with..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected the tool to complete the scan and generate a report..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Run `git-security-audit --type comprehensive`
        2. Wait for scan to complete
        3. See error message...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Output
      description: |
        Please copy and paste any relevant log output. 
        ⚠️ Make sure to redact any sensitive information!
      render: shell

  - type: textarea
    id: repository_info
    attributes:
      label: Repository Information
      description: |
        Information about the repository being scanned (no sensitive data!)
      placeholder: |
        - Repository size: ~500 commits
        - Branches: 5-10 active branches  
        - File types: JavaScript, Python, Docker
        - Estimated age: 2 years
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I am using the latest version of the tool
          required: true
        - label: I have redacted any sensitive information from logs/output
          required: true
        - label: I can reproduce this issue consistently
          required: false

---
