name: 🔒 Security Vulnerability
description: Report a security vulnerability (private disclosure)
title: "[Security]: "
labels: ["security", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ STOP - Read This First
        
        If this is a **security vulnerability**, please **DO NOT** submit it here.
        
        Instead, please report it privately via:
        - 📧 Email: security@git-security-audit.com
        - 🔒 GitHub Security: Use the "Security" tab → "Report a vulnerability"
        
        **Why private reporting?**
        - Protects users while we develop a fix
        - Prevents exploitation by bad actors
        - Allows coordinated disclosure
        
        ---
        
        If this is **NOT** a security vulnerability, please use the appropriate template:
        - 🐛 [Bug Report](https://github.com/username/git-security-audit/issues/new?template=bug_report.yml)
        - 💡 [Feature Request](https://github.com/username/git-security-audit/issues/new?template=feature_request.yml)

  - type: checkboxes
    id: confirm_security
    attributes:
      label: Confirmation
      description: Please confirm this is appropriate for public disclosure
      options:
        - label: This is NOT a security vulnerability that could harm users
          required: true
        - label: I understand that security vulnerabilities should be reported privately
          required: true

  - type: textarea
    id: public_security_concern
    attributes:
      label: Public Security Discussion
      description: |
        If you want to discuss security best practices, improvements to our security model,
        or general security questions that don't involve vulnerabilities, please describe here.
      placeholder: |
        Example topics:
        - Suggestions for security improvements
        - Questions about our security model
        - Discussion of security best practices
        - General security hardening ideas

---

